/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_3dd53475 (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/vpvpbdwtyugbknrntkho/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2";

const supabaseUrl = Deno.env.get("SUPABASE_URL")!;
const supabaseKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;

const supabase = createClient(supabaseUrl, supabaseKey);

// ✅ SQL-ONLY: No memory cache, no timeout fallback
// All operations must use SQL database. Fail fast if DB unavailable.

export async function get(key: string): Promise<string | null> {
  console.log(`🔍 [KV-GET] Fetching key: ${key}`);
  
  try {
    const result = await supabase
      .from("kv_store_3dd53475")
      .select("value")
      .eq("key", key)
      .maybeSingle();

    if (result.error) {
      console.error(`❌ [KV-GET] Error fetching ${key}:`, result.error);
      throw new Error(`Database error: ${result.error.message}`);
    }

    console.log(`✅ [KV-GET] Successfully fetched ${key}:`, result.data?.value ? 'found' : 'not found');
    return result.data?.value || null;
  } catch (error: unknown) {
    console.error(`❌ [KV-GET] Exception fetching ${key}:`, error);
    throw error; // Fail fast - no cache fallback
  }
}

export async function set(key: string, value: string): Promise<void> {
  console.log(`💾 [KV-SET] Setting key: ${key}`);
  
  try {
    const result = await supabase
      .from("kv_store_3dd53475")
      .upsert({ key, value }, { onConflict: "key" });

    if (result.error) {
      console.error(`❌ [KV-SET] Error setting ${key}:`, result.error);
      throw new Error(`Database error: ${result.error.message}`);
    }

    console.log(`✅ [KV-SET] Successfully set ${key}`);
  } catch (error: unknown) {
    console.error(`❌ [KV-SET] Exception setting ${key}:`, error);
    throw error; // Fail fast - no cache fallback
  }
}

export async function del(key: string): Promise<void> {
  console.log(`🗑️ [KV-DEL] Deleting key: ${key}`);
  
  try {
    const result = await supabase
      .from("kv_store_3dd53475")
      .delete()
      .eq("key", key);

    if (result.error) {
      console.error(`❌ [KV-DEL] Error deleting ${key}:`, result.error);
      throw new Error(`Database error: ${result.error.message}`);
    }

    console.log(`✅ [KV-DEL] Successfully deleted ${key}`);
  } catch (error: unknown) {
    console.error(`❌ [KV-DEL] Exception deleting ${key}:`, error);
    throw error; // Fail fast - no cache fallback
  }
}

export async function mget(keys: string[]): Promise<Map<string, string>> {
  console.log(`🔍 [KV-MGET] Fetching ${keys.length} keys`);
  
  try {
    const result = await supabase
      .from("kv_store_3dd53475")
      .select("key, value")
      .in("key", keys);

    if (result.error) {
      console.error(`❌ [KV-MGET] Error fetching multiple keys:`, result.error);
      throw new Error(`Database error: ${result.error.message}`);
    }

    const map = new Map<string, string>();
    result.data.forEach((row: { key: string; value: string }) => {
      map.set(row.key, row.value);
    });

    console.log(`✅ [KV-MGET] Successfully fetched ${map.size} values`);
    return map;
  } catch (error: unknown) {
    console.error(`❌ [KV-MGET] Exception:`, error);
    throw error; // Fail fast - no cache fallback
  }
}

export async function getByPrefix(prefix: string): Promise<{ key: string; value: string }[]> {
  console.log(`🔍 [KV-PREFIX] Fetching keys with prefix: ${prefix}`);
  
  try {
    const result = await supabase
      .from("kv_store_3dd53475")
      .select("key, value")
      .ilike("key", `${prefix}%`);

    if (result.error) {
      console.error(`❌ [KV-PREFIX] Error fetching by prefix ${prefix}:`, result.error);
      throw new Error(`Database error: ${result.error.message}`);
    }

    console.log(`✅ [KV-PREFIX] Found ${result.data.length} keys with prefix ${prefix}`);
    return result.data as { key: string; value: string }[];
  } catch (error: unknown) {
    console.error(`❌ [KV-PREFIX] Exception:`, error);
    throw error; // Fail fast - no cache fallback
  }
}

export async function mset(entries: Array<[string, string]>): Promise<void> {
  console.log(`💾 [KV-MSET] Setting ${entries.length} keys`);
  
  try {
    const rows = entries.map(([key, value]) => ({ key, value }));
    const result = await supabase
      .from("kv_store_3dd53475")
      .upsert(rows, { onConflict: "key" });

    if (result.error) {
      console.error(`❌ [KV-MSET] Error setting multiple keys:`, result.error);
      throw new Error(`Database error: ${result.error.message}`);
    }

    console.log(`✅ [KV-MSET] Successfully set ${entries.length} keys`);
  } catch (error: unknown) {
    console.error(`❌ [KV-MSET] Exception:`, error);
    throw error; // Fail fast - no cache fallback
  }
}

export async function mdel(keys: string[]): Promise<void> {
  console.log(`🗑️ [KV-MDEL] Deleting ${keys.length} keys`);
  
  try {
    const result = await supabase
      .from("kv_store_3dd53475")
      .delete()
      .in("key", keys);

    if (result.error) {
      console.error(`❌ [KV-MDEL] Error deleting multiple keys:`, result.error);
      throw new Error(`Database error: ${result.error.message}`);
    }

    console.log(`✅ [KV-MDEL] Successfully deleted ${keys.length} keys`);
  } catch (error: unknown) {
    console.error(`❌ [KV-MDEL] Exception:`, error);
    throw error; // Fail fast - no cache fallback
  }
}