#!/bin/bash

# Simplified Deployment Script
# For systems without Homebrew/GitHub CLI

echo "╔═══════════════════════════════════════════════════════════╗"
echo "║      Warmpawz Deployment - Quick Start Guide             ║"
echo "╚═══════════════════════════════════════════════════════════╝"
echo ""
echo "✅ AWS Credentials: Configured"
echo "✅ AWS Account: 023394150666"
echo "✅ AWS Region: ap-south-1"
echo "✅ AWS Secrets: Created (dev environment)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📋 NEXT STEPS:"
echo ""
echo "1️⃣  INSTALL TERRAFORM"
echo "    → Download from: https://www.terraform.io/downloads"
echo "    → Or use package manager"
echo ""
echo "2️⃣  SET UP GITHUB SECRETS (Choose one option):"
echo ""
echo "    Option A: Use GitHub Web Interface"
echo "    ┌─────────────────────────────────────────────────┐"
echo "    │ 1. Go to your GitHub repository                 │"
echo "    │ 2. Settings → Secrets and variables → Actions   │"
echo "    │ 3. Click 'New repository secret'                │"
echo "    │ 4. Add these secrets:                           │"
echo "    │                                                  │"
echo "    │    AWS_ACCESS_KEY_ID                            │"
echo "    │    AWS_SECRET_ACCESS_KEY                        │"
echo "    │    AWS_REGION (ap-south-1)                      │"
echo "    │    AWS_ACCOUNT_ID (023394150666)                │"
echo "    │    RAZORPAY_KEY_ID                              │"
echo "    │    RAZORPAY_KEY_SECRET                          │"
echo "    │    GOOGLE_MAPS_API_KEY                          │"
echo "    │    SHIPROCKET_EMAIL                             │"
echo "    │    SHIPROCKET_PASSWORD                          │"
echo "    │    DEV_OPENSEARCH_PASSWORD                      │"
echo "    │    STAGE_OPENSEARCH_PASSWORD                    │"
echo "    │    PROD_OPENSEARCH_PASSWORD                     │"
echo "    │                                                  │"
echo "    │ See DEPLOY_MANUAL_STEPS.md for values          │"
echo "    └─────────────────────────────────────────────────┘"
echo ""
echo "    Option B: Install GitHub CLI"
echo "    ┌─────────────────────────────────────────────────┐"
echo "    │ Download: https://cli.github.com/               │"
echo "    │                                                  │"
echo "    │ Then run: ./scripts/setup-github-secrets.sh     │"
echo "    └─────────────────────────────────────────────────┘"
echo ""
echo "3️⃣  CREATE GITHUB ENVIRONMENTS"
echo "    ┌─────────────────────────────────────────────────┐"
echo "    │ Settings → Environments → New environment       │"
echo "    │                                                  │"
echo "    │ Create:                                          │"
echo "    │   - dev (no protection)                          │"
echo "    │   - stage (1 reviewer)                           │"
echo "    │   - stage-approval (1 reviewer)                  │"
echo "    │   - production (2 reviewers)                     │"
echo "    │   - production-approval (2 reviewers)            │"
echo "    └─────────────────────────────────────────────────┘"
echo ""
echo "4️⃣  BOOTSTRAP TERRAFORM STATE"
echo "    Run these commands:"
echo "    ┌─────────────────────────────────────────────────┐"
echo "    │ cd infra/bootstrap                               │"
echo "    │ terraform init                                   │"
echo "    │ terraform apply \\                               │"
echo "    │   -var='create_state_backend=true' \\           │"
echo "    │   -var='aws_account_id=023394150666'            │"
echo "    └─────────────────────────────────────────────────┘"
echo ""
echo "5️⃣  DEPLOY TO DEV"
echo "    ┌─────────────────────────────────────────────────┐"
echo "    │ git checkout -b develop                          │"
echo "    │ git add .                                        │"
echo "    │ git commit -m 'feat: initial setup'             │"
echo "    │ git push origin develop                          │"
echo "    │                                                  │"
echo "    │ ✨ This triggers automatic deployment!          │"
echo "    └─────────────────────────────────────────────────┘"
echo ""
echo "6️⃣  DEPLOY TO STAGE"
echo "    ┌─────────────────────────────────────────────────┐"
echo "    │ git checkout main                                │"
echo "    │ git merge develop                                │"
echo "    │ git push origin main                             │"
echo "    │                                                  │"
echo "    │ ⚠️  Requires 1 reviewer approval                │"
echo "    └─────────────────────────────────────────────────┘"
echo ""
echo "7️⃣  DEPLOY TO PRODUCTION"
echo "    ┌─────────────────────────────────────────────────┐"
echo "    │ 1. Go to GitHub Actions                          │"
echo "    │ 2. Select 'Deploy to Production'                 │"
echo "    │ 3. Click 'Run workflow'                          │"
echo "    │ 4. Type: DEPLOY_TO_PRODUCTION                    │"
echo "    │ 5. Click 'Run workflow'                          │"
echo "    │                                                  │"
echo "    │ ⚠️  Requires 2 reviewers approval               │"
echo "    └─────────────────────────────────────────────────┘"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "⚠️  CRITICAL SECURITY REMINDER"
echo ""
echo "After deployment, IMMEDIATELY rotate all credentials!"
echo "See: SECURITY_WARNING.md for instructions"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "📚 Helpful Documents:"
echo "   • DEPLOY_MANUAL_STEPS.md - Detailed step-by-step guide"
echo "   • SECURITY_WARNING.md - Security and rotation guide"
echo "   • GITHUB_SECRETS_COMPLETE_LIST.md - All secrets reference"
echo "   • docs/DEPLOYMENT_GUIDE.md - Comprehensive guide"
echo ""
echo "🔍 Check Status:"
echo "   • GitHub Secrets: Settings → Secrets and variables"
echo "   • AWS Secrets: aws secretsmanager list-secrets --region ap-south-1"
echo "   • Deployments: GitHub → Actions"
echo ""
echo "Good luck with your deployment! 🚀"

