#!/bin/bash
echo "=== Testing Customer Web Endpoints ==="
echo ""

# Extract all unique endpoints from customer components
ENDPOINTS=(
  "/customer/vendors/search"
  "/customer/notifications"
  "/notifications/mark-read"
  "/notifications/mark-all-read"
  "/notifications/:id"
  "/customer/behavior-journal"
  "/customer/questionnaire/planning"
  "/customer/profile"
  "/customer/pets"
  "/customer/search/track"
  "/customer/cart/:phone/items/:itemId"
  "/customer/saved/:phone/items/:itemId"
  "/customer/:phone/addresses"
  "/customer/payments/:phone"
  "/customer/notifications/:phone"
  "/payments/verify"
  "/customer/auth/request-otp"
  "/customer/auth/verify-otp"
  "/customer/referrals/apply"
  "/customer/bookings/refund-preview"
  "/customer/services/request"
  "/customer/search/history"
  "/customer/:phone/pets/:petId"
  "/customer/:phone/pets/:petId/bookings"
  "/customer/pets/:petId"
  "/customer/bookings"
  "/customer/bookings/:bookingId"
  "/tracking/session/:bookingId"
  "/customer/onboarding"
  "/prescription/booking/:bookingId"
  "/customer/refunds/request"
  "/chat/send"
  "/chat/upload-file"
  "/vendor/:vendorId/slots/:date"
  "/followup/create"
  "/appointment/:appointmentId"
  "/appointment/:appointmentId/cancel"
  "/appointment/:appointmentId/reschedule"
  "/appointment/customer/:customerId"
  "/bookings/:bookingId/reschedule"
  "/vendor/reschedule-policy"
  "/vendor/available-slots"
  "/booking/create"
  "/trainer/book-free-trial"
  "/behaviorist/journal-entry"
)

echo "Total endpoints to check: ${#ENDPOINTS[@]}"
echo ""
