#!/bin/bash

# Warmpawz Edge Function Deployment Verification Script
# This script checks if the Edge Function is properly deployed and working

set -e

# Configuration
PROJECT_ID="vpvpbdwtyugbknrntkho"
BASE_URL="https://${PROJECT_ID}.supabase.co/functions/v1/make-server-3dd53475"

# Colors for output
GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Warmpawz Deployment Verification${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Check if curl is installed
if ! command_exists curl; then
    echo -e "${RED}❌ curl is not installed${NC}"
    echo "Please install curl to run this script"
    exit 1
fi

echo -e "${BLUE}📍 Project ID:${NC} $PROJECT_ID"
echo -e "${BLUE}🔗 Base URL:${NC} $BASE_URL"
echo ""

# Check if ANON_KEY is provided
if [ -z "$SUPABASE_ANON_KEY" ]; then
    echo -e "${YELLOW}⚠️  SUPABASE_ANON_KEY environment variable not set${NC}"
    echo "Set it with: export SUPABASE_ANON_KEY=your_key_here"
    echo ""
    echo "Running tests without authentication (may fail)..."
    echo ""
    AUTH_HEADER=""
else
    echo -e "${GREEN}✅ SUPABASE_ANON_KEY found${NC}"
    AUTH_HEADER="Authorization: Bearer $SUPABASE_ANON_KEY"
fi

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Running Tests${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Test 1: Health Check
echo -e "${BLUE}1️⃣  Testing Health Endpoint${NC}"
echo "   GET $BASE_URL/health"
echo ""

HEALTH_RESPONSE=$(curl -s -w "\n%{http_code}" -H "$AUTH_HEADER" "$BASE_URL/health" 2>&1)
HTTP_CODE=$(echo "$HEALTH_RESPONSE" | tail -n 1)
RESPONSE_BODY=$(echo "$HEALTH_RESPONSE" | sed '$d')

if [ "$HTTP_CODE" = "200" ]; then
    echo -e "${GREEN}   ✅ Health check passed${NC}"
    echo "   Response: $RESPONSE_BODY"
else
    echo -e "${RED}   ❌ Health check failed${NC}"
    echo "   HTTP Code: $HTTP_CODE"
    echo "   Response: $RESPONSE_BODY"
    echo ""
    echo -e "${RED}🚨 Edge Function is NOT deployed or not responding${NC}"
    echo ""
    echo "To deploy, run:"
    echo "  supabase functions deploy server"
    echo ""
    echo "See DEPLOYMENT_GUIDE.md for detailed instructions"
    exit 1
fi

echo ""

# Test 2: Dynamic Form Endpoint
echo -e "${BLUE}2️⃣  Testing Dynamic Form Endpoint${NC}"
echo "   GET $BASE_URL/admin/onboarding-forms/pet_clinic"
echo ""

FORM_RESPONSE=$(curl -s -w "\n%{http_code}" -H "$AUTH_HEADER" "$BASE_URL/admin/onboarding-forms/pet_clinic" 2>&1)
HTTP_CODE=$(echo "$FORM_RESPONSE" | tail -n 1)
RESPONSE_BODY=$(echo "$FORM_RESPONSE" | sed '$d')

if [ "$HTTP_CODE" = "200" ]; then
    echo -e "${GREEN}   ✅ Dynamic form endpoint working${NC}"
    
    # Check if form was auto-generated
    if echo "$RESPONSE_BODY" | grep -q "autoGenerated"; then
        echo -e "${GREEN}   🎉 Auto-generation is working!${NC}"
    fi
    
    # Extract form status
    if echo "$RESPONSE_BODY" | grep -q '"status":"active"'; then
        echo -e "${GREEN}   📋 Form status: active${NC}"
    fi
else
    echo -e "${RED}   ❌ Dynamic form endpoint failed${NC}"
    echo "   HTTP Code: $HTTP_CODE"
    echo "   Response: $RESPONSE_BODY"
fi

echo ""

# Test 3: Check all vendor roles
echo -e "${BLUE}3️⃣  Testing All Vendor Roles${NC}"
echo ""

ROLES=("pet_clinic" "pet_groomer" "pet_trainer" "pet_sitter" "pet_walker" "pet_boarding" "pet_store" "pet_insurance")
SUCCESS_COUNT=0
FAIL_COUNT=0

for ROLE in "${ROLES[@]}"; do
    ROLE_RESPONSE=$(curl -s -w "\n%{http_code}" -H "$AUTH_HEADER" "$BASE_URL/admin/onboarding-forms/$ROLE" 2>&1)
    HTTP_CODE=$(echo "$ROLE_RESPONSE" | tail -n 1)
    
    if [ "$HTTP_CODE" = "200" ]; then
        echo -e "   ${GREEN}✅ $ROLE${NC}"
        ((SUCCESS_COUNT++))
    else
        echo -e "   ${RED}❌ $ROLE (HTTP $HTTP_CODE)${NC}"
        ((FAIL_COUNT++))
    fi
done

echo ""
echo -e "${BLUE}   Results: $SUCCESS_COUNT passed, $FAIL_COUNT failed${NC}"

echo ""
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}  Summary${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

if [ $FAIL_COUNT -eq 0 ]; then
    echo -e "${GREEN}🎉 All tests passed! Edge Function is working correctly.${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. ✅ Test vendor onboarding in the app"
    echo "  2. ✅ Verify forms load in the frontend"
    echo "  3. ✅ Customize forms via Admin Dashboard (optional)"
else
    echo -e "${YELLOW}⚠️  Some tests failed. Check the errors above.${NC}"
    echo ""
    echo "Common fixes:"
    echo "  - Ensure Edge Function is deployed: supabase functions deploy server"
    echo "  - Check function logs: supabase functions logs server --tail"
    echo "  - Verify ANON_KEY is correct"
fi

echo ""
echo -e "${BLUE}📚 For more help, see:${NC}"
echo "   - DEPLOYMENT_GUIDE.md"
echo "   - https://supabase.com/docs/guides/functions"
echo ""
