-- H2 (PostgreSQL mode): bookings columns required for create / cancel / reschedule paths.
-- Mirrors db/schemas/booking/bookings.sql + 541 + 616 + 621 + 753 (no FKs — UUID refs only).

CREATE TABLE IF NOT EXISTS bookings (
    id UUID PRIMARY KEY,
    customer_id UUID NOT NULL,
    vendor_id UUID,
    staff_id UUID,
    service_id UUID NOT NULL,
    booking_date DATE NOT NULL,
    booking_time TIME NOT NULL,
    status VARCHAR(64) NOT NULL DEFAULT 'pending',
    service_type VARCHAR(32) NOT NULL,
    address VARCHAR(4096),
    city VARCHAR(128),
    state VARCHAR(128),
    pincode VARCHAR(16),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    base_price DECIMAL(10, 2) NOT NULL,
    discount_amount DECIMAL(10, 2) DEFAULT 0,
    tax_amount DECIMAL(10, 2) DEFAULT 0,
    total_amount DECIMAL(10, 2) NOT NULL,
    loyalty_points_used INT DEFAULT 0,
    coupon_code VARCHAR(80),
    promotion_id UUID,
    is_package BOOLEAN DEFAULT FALSE,
    package_id UUID,
    package_details VARCHAR(10000),
    payment_status VARCHAR(32) DEFAULT 'pending',
    payment_id UUID,
    otp_code VARCHAR(32),
    otp_verified BOOLEAN DEFAULT FALSE,
    otp_expires_at TIMESTAMP,
    notes VARCHAR(4096),
    cancellation_reason VARCHAR(512),
    rescheduled_from_booking_id UUID,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    cancelled_at TIMESTAMP,
    settled_at TIMESTAMP,
    customer_phone VARCHAR(20),
    duration_minutes INT,
    total_duration_minutes INT,
    pet_id UUID,
    selected_services VARCHAR(10000),
    subscription_id UUID,
    subscription_booking BOOLEAN DEFAULT FALSE,
    room_id UUID,
    package_purchase_id UUID,
    is_package_session BOOLEAN DEFAULT FALSE,
    package_session_number INT,
    estimated_arrival TIMESTAMP,
    address_line1 VARCHAR(512),
    address_line2 VARCHAR(512),
    service_style VARCHAR(64),
    flow_variant VARCHAR(64),
    reschedule_reason VARCHAR(512),
    otp_verified_at TIMESTAMP,
    vendor_timezone VARCHAR(64) DEFAULT 'Asia/Kolkata',
    check_out_date DATE,
    check_out_time TIME,
    cancelled_by VARCHAR(32),
    penalty_processed BOOLEAN DEFAULT FALSE
);
