import type { Hono } from 'hono';
import { registerAdoptionPetsGetRoute } from './routes/adoption_pets_get.route';
import { registerAdoptionPetsPetidGetRoute } from './routes/adoption_pets_petid_get.route';
import { registerAdoptionQuestionnairePostRoute } from './routes/adoption_questionnaire_post.route';
import { registerAdoptionRequestPostRoute } from './routes/adoption_request_post.route';
import { registerBreederPuppiesGetRoute } from './routes/breeder_puppies_get.route';
import { registerBreederInquiryPostRoute } from './routes/breeder_inquiry_post.route';
import { registerBreederReservePostRoute } from './routes/breeder_reserve_post.route';
import { registerCustomerPetmatchingGetRoute } from './routes/customer_petmatching_get.route';
import { registerCustomerPetmatchingRequestPostRoute } from './routes/customer_petmatching_request_post.route';
import { registerCustomerPetmatchingRequestsGetRoute } from './routes/customer_petmatching_requests_get.route';
import { registerCustomerPetmatchingRequestsRequestidPutRoute } from './routes/customer_petmatching_requests_requestid_put.route';
import { registerCustomerHolidaypackagesGetRoute } from './routes/customer_holidaypackages_get.route';
import { registerHolidaysBuildpackagePostRoute } from './routes/holidays_buildpackage_post.route';
import { registerRelocationServicesGetRoute } from './routes/relocation_services_get.route';
import { registerRelocationQuotePostRoute } from './routes/relocation_quote_post.route';
import { registerRelocationBookPostRoute } from './routes/relocation_book_post.route';
import { registerVendorVendoridAdoptionPetsGetRoute } from './routes/vendor_vendorid_adoption_pets_get.route';
import { registerVendorVendoridAdoptionPetsPostRoute } from './routes/vendor_vendorid_adoption_pets_post.route';
import { registerVendorVendoridAdoptionPetsPetidPutRoute } from './routes/vendor_vendorid_adoption_pets_petid_put.route';
import { registerVendorVendoridAdoptionapplicationsGetRoute } from './routes/vendor_vendorid_adoptionapplications_get.route';
import { registerVendorVendoridAdoptionapplicationsApplicationidPutRoute } from './routes/vendor_vendorid_adoptionapplications_applicationid_put.route';
import { registerVendorVendoridRelocationquotesGetRoute } from './routes/vendor_vendorid_relocationquotes_get.route';
import { registerVendorVendoridRelocationquotesQuoteidRespondPostRoute } from './routes/vendor_vendorid_relocationquotes_quoteid_respond_post.route';
import { registerVendorVendoridHolidaycustomrequestsGetRoute } from './routes/vendor_vendorid_holidaycustomrequests_get.route';
import { registerVendorVendoridMatingrequestsGetRoute } from './routes/vendor_vendorid_matingrequests_get.route';

export function registerSpecializedServiceFlows(app: Hono) {
  registerAdoptionPetsGetRoute(app);
  registerAdoptionPetsPetidGetRoute(app);
  registerAdoptionQuestionnairePostRoute(app);
  registerAdoptionRequestPostRoute(app);
  registerBreederPuppiesGetRoute(app);
  registerBreederInquiryPostRoute(app);
  registerBreederReservePostRoute(app);
  registerCustomerPetmatchingGetRoute(app);
  registerCustomerPetmatchingRequestPostRoute(app);
  registerCustomerPetmatchingRequestsGetRoute(app);
  registerCustomerPetmatchingRequestsRequestidPutRoute(app);
  registerCustomerHolidaypackagesGetRoute(app);
  registerHolidaysBuildpackagePostRoute(app);
  registerRelocationServicesGetRoute(app);
  registerRelocationQuotePostRoute(app);
  registerRelocationBookPostRoute(app);
  registerVendorVendoridAdoptionPetsGetRoute(app);
  registerVendorVendoridAdoptionPetsPostRoute(app);
  registerVendorVendoridAdoptionPetsPetidPutRoute(app);
  registerVendorVendoridAdoptionapplicationsGetRoute(app);
  registerVendorVendoridAdoptionapplicationsApplicationidPutRoute(app);
  registerVendorVendoridRelocationquotesGetRoute(app);
  registerVendorVendoridRelocationquotesQuoteidRespondPostRoute(app);
  registerVendorVendoridHolidaycustomrequestsGetRoute(app);
  registerVendorVendoridMatingrequestsGetRoute(app);
}
