import { defineSpecialization } from '../../define';
import { trainingBenefits } from './training-content-helpers';
import { trainingServiceModes } from './training-service-mode-defaults';

export const aggressionMetadata = defineSpecialization({
  id: 'aggression',
  aliases: ['aggression_fix', 'agression_fix'],
  category: 'training',
  title: 'Aggression Fix',
  description:
    'Behaviour-focused training designed to understand triggers, manage difficult responses and build safer, more appropriate behaviour.',
  heroImage: '/images/home/Training/aggression-fix-training.webp',
  heroImagePosition: 'center 30%',
  highlightChips: ['Behaviour Correction', 'Trigger Management', 'Positive Training'],
  whatsIncluded: [],
  behavioursAddressed: [
    'Aggression towards people',
    'Aggression towards other animals',
    'Excessive barking',
    'Leash pulling',
    'Lunging',
    'Leash reactivity',
    'Fear',
    'Anxiety',
    'Separation-related anxiety',
    'Resource guarding',
    'Excessive jumping',
    'Mouthing',
    'Destructive behaviour',
    'Unwanted chasing',
    'Difficulty settling',
    'Hyperactivity',
    'Fear of handling',
    'Fear of grooming',
    'Fear of veterinary visits',
    'Socialisation difficulties',
  ],
  trainerDeliversTitle: 'What the Behaviourist Does',
  trainerDelivers: [
    "Observes the pet's behaviour",
    'Identifies possible triggers',
    'Understands behavioural patterns',
    'Assesses the home/environment',
    'Reviews daily routine',
    'Assesses interactions with family members and other pets',
    'Demonstrates behaviour-management techniques',
    'Creates a personalised behaviour modification plan',
    'Teaches the pet parent how to reinforce desirable behaviour',
    'Teaches safe trigger-management techniques',
    'Recommends follow-up sessions where required',
  ],
  benefits: trainingBenefits([
    { title: 'Better understanding of behavioural triggers', icon: 'brain' },
    { title: 'Safer behaviour management', icon: 'shield' },
    { title: 'Improved emotional regulation', icon: 'heart' },
    { title: 'Better pet-parent understanding', icon: 'graduation' },
    { title: 'Structured behaviour improvement', icon: 'check' },
  ]),
  whoIsThisFor: ['Pets showing recurring, difficult or disruptive behavioural concerns'],
  audienceTitle: 'Who Is This Training For?',
  timeline: [],
  tips: [],
  importantNotes: [
    'Behaviour modification is not simply about teaching commands.',
    'It focuses on understanding what triggers the behaviour and how the pet responds, followed by appropriate management and behaviour-change techniques.',
    'This service is not medical treatment and does not include medical or diagnostic claims.',
  ],
  serviceModeInformation: trainingServiceModes({
    at_home: {
      title: 'Behaviour Review & Correction – At Home',
      description:
        "Best suited for behaviour that primarily occurs in the pet's regular home environment.",
      details: [
        'Observe behaviour in normal surroundings',
        'Identify household triggers',
        'Assess family/pet interactions',
        'Review routine and enrichment',
        'Demonstrate management techniques',
        'Create a personalised plan',
        'Guide the pet parent',
      ],
    },
    at_center: {
      title: 'Behaviour Review & Correction – At Centre',
      description: 'Best suited for controlled work on specific behavioural challenges.',
      details: [
        'Behaviour assessment',
        'Trigger identification',
        'Controlled exposure where appropriate',
        'Focus and emotional regulation',
        'Desensitisation where appropriate',
        'Counter-conditioning where appropriate',
        'Controlled interaction where appropriate',
        'Leash reactivity management',
        'Confidence building',
        'Alternative behaviour training',
        'Home exercises for the pet parent',
      ],
    },
  }),
});
