/**
 * Back-intent helpers — re-exported from go-back-or-replace for NavigationService consumers.
 * Existing call sites keep importing from @/lib/go-back-or-replace.
 */
export {
  goBackOrReplace,
  goBackOrHome,
  clearShopBackIntent,
  clearWishlistOpenedFromShopMark,
  rememberShopBackFromCurrentUrl,
  rememberShopBackToSpaScreen,
  handleShopPageBack,
  rememberPromotionsBackFromCurrentUrl,
  rememberPromotionsBackSpaScreen,
  handlePromotionsPageBack,
  rememberHelpBackFromCurrentUrl,
  rememberHelpBackSpaScreen,
  handleHelpPageBack,
  rememberOrdersBackFromCurrentUrl,
  rememberOrdersBackToSpaScreen,
  handleOrdersPageBack,
  rememberWalletChildBackFromCurrentUrl,
  rememberWalletChildBackSpaScreen,
  handleWalletChildPageBack,
  rememberSubscriptionsBackFromCurrentUrl,
  rememberSubscriptionsBackSpaScreen,
  handleSubscriptionsPageBack,
  rememberMyPackagesBackFromAccountMenu,
  rememberMyPackagesBackFromCurrentUrl,
  handleMyPackagesPageBack,
  rememberWpayHistoryBackFromAccountMenu,
  rememberWpayHistoryBackFromCurrentUrl,
  rememberBeforeWpayHistoryNav,
  handleWpayHistoryPageBack,
  navigateAfterMealOrderPlaced,
  WARMPAWZ_OPEN_SCREEN_AFTER_NAV_KEY,
  WARMPAWZ_HOME_RESUME_SCREENS,
} from '@/lib/go-back-or-replace';
