export const CATEGORY_ROLES: Record<string, string[]> = {
    vet: ['veterinarian', 'vet_clinic', 'vet_solo', 'vet', 'Veterinarian'],
    grooming: ['groomer', 'grooming_salon', 'pet_groomer', 'groomer_center', 'groomer_solo', 'grooming_solo'],
    training: ['trainer', 'pet_trainer', 'trainer_center', 'trainer_solo', 'training_solo'],
    nutritionist: ['nutritionist', 'pet_nutritionist', 'nutritionist_center', 'nutritionist_solo'],
    nutrition: ['nutritionist', 'pet_nutritionist', 'nutritionist_center', 'nutritionist_solo'],
    walker: ['walker', 'pet_walker', 'dog_walker', 'walker_solo'],
    boarding: ['boarding', 'pet_boarder', 'pet_boarding'],
    adoption: ['adoption_center', 'pet_shelter', 'pet_adoption_center'],
    shop: ['seller', 'pet_products_store'],
    cafe: ['cafe', 'pet_cafe'],
    cafes: ['cafe', 'pet_cafe'],
    photography: ['photographer', 'pet_photographer'],
    insurance: ['insurance', 'pet_insurance'],
    ambulance: ['ambulance', 'pet_ambulance'],
    breeder: ['breeder', 'pet_breeder'],
    relocation: ['relocation', 'pet_taxi', 'pet_transport', 'pet_relocation'],
    resort: ['resort', 'pet_resort'],
    holiday: ['holiday'],
    sunset: ['sunset', 'pet_sunset_services'],
    behaviourist: ['behaviourist', 'pet_behaviourist', 'behaviourist_solo'],
    sitting: ['pet_sitter', 'sitter', 'sitter_solo'],
    diagnostics: ['diagnostics_center', 'diagnostics_provider', 'diagnostics_solo'],
    'lab-diagnostics': ['diagnostics_center', 'diagnostics_provider', 'diagnostics_solo'],
};