/**
 * Delhivery Integration for Warmpawz
 * Handles B2C logistics, COD, and pan-India delivery
 * API Docs: https://one.delhivery.com/developer-portal/documents/b2c/
 */

// ✅ SQL MIGRATION: All KV operations replaced with SQL repositories
import { Hono } from 'hono';
import { getPlatformSettingsRepository } from '../../../supabase/lib/repositories/index';

const DELHIVERY_API_BASE = 'https://track.delhivery.com/api';
const DELHIVERY_SURFACE_API = 'https://track.delhivery.com/api/cmu/create.json';

// Token management
let delhiveryToken: string | null = null;

/**
 * Get Delhivery API Token from settings
 */
async function getDelhiveryToken(): Promise<string | null> {
  if (delhiveryToken) return delhiveryToken;

  try {
    // ✅ SQL: Get logistics partners from platform settings
    const platformSettingsRepo = getPlatformSettingsRepository();
    const partners = await platformSettingsRepo.getLogisticsPartners();
    const delhivery = partners.find((p: any) => p.partner_id === 'delhivery' && p.enabled);

    if (!delhivery || !delhivery.api_key) {
      console.log('[Delhivery] No API key found in settings');
      return null;
    }

    delhiveryToken = delhivery.api_key;
    return delhiveryToken;
  } catch (error) {
    console.error('[Delhivery] Error fetching token:', error);
    return null;
  }
}

/**
 * Create Delhivery Shipment
 */
export async function createDelhiveryShipment(orderData: any) {
  try {
    const token = await getDelhiveryToken();
    if (!token) {
      throw new Error('Delhivery API token not configured');
    }

    // Prepare shipment data according to Delhivery API format
    const shipmentData = {
      shipments: [{
        name: orderData.customerName,
        add: orderData.shippingAddress.street,
        add_2: orderData.shippingAddress.landmark || '',
        city: orderData.shippingAddress.city,
        pin: orderData.shippingAddress.pincode,
        state: orderData.shippingAddress.state,
        country: 'India',
        phone: orderData.customerPhone,
        email: orderData.customerEmail || '',
        order: orderData.orderId,
        payment_mode: orderData.paymentMethod === 'cod' ? 'COD' : 'Prepaid',
        return_name: orderData.sellerName || 'Warmpawz Seller',
        return_add: orderData.pickupAddress?.street || '',
        return_city: orderData.pickupAddress?.city || '',
        return_pin: orderData.pickupAddress?.pincode || '',
        return_state: orderData.pickupAddress?.state || '',
        return_country: 'India',
        return_phone: orderData.pickupAddress?.phone || '',
        products_desc: orderData.items.map((i: any) => i.name).join(', '),
        hsn_code: orderData.items[0]?.hsn || '',
        cod_amount: orderData.paymentMethod === 'cod' ? orderData.totalAmount : 0,
        order_date: orderData.orderDate || new Date().toISOString().split('T')[0],
        total_amount: orderData.totalAmount,
        seller_add: orderData.pickupAddress?.street || '',
        seller_name: orderData.sellerName || 'Warmpawz',
        seller_inv: orderData.invoiceNumber || orderData.orderId,
        quantity: orderData.items.reduce((sum: number, i: any) => sum + i.quantity, 0),
        waybill: '', // Will be generated by Delhivery
        shipment_width: orderData.width || 10,
        shipment_height: orderData.height || 10,
        weight: orderData.weight || 0.5,
        seller_gst_tin: orderData.sellerGST || '',
        shipping_mode: orderData.shippingMode || 'Surface',
        address_type: orderData.addressType || 'home'
      }]
    };

    const formData = new URLSearchParams();
    formData.append('format', 'json');
    formData.append('data', JSON.stringify(shipmentData));

    const response = await fetch(DELHIVERY_SURFACE_API, {
      method: 'POST',
      headers: {
        'Authorization': `Token ${token}`,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: formData.toString()
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Delhivery shipment creation failed: ${JSON.stringify(error)}`);
    }

    const result = await response.json();
    console.log('✅ Delhivery shipment created:', orderData.orderId);
    return result;
  } catch (error) {
    console.error('❌ Delhivery shipment creation error:', error);
    throw error;
  }
}

/**
 * Track Shipment by Waybill
 */
export async function trackDelhiveryShipment(waybill: string) {
  try {
    const token = await getDelhiveryToken();
    if (!token) {
      throw new Error('Delhivery API token not configured');
    }

    const response = await fetch(`${DELHIVERY_API_BASE}/v1/packages/json/?waybill=${waybill}`, {
      headers: {
        'Authorization': `Token ${token}`,
      }
    });

    if (!response.ok) {
      throw new Error('Failed to track Delhivery shipment');
    }

    const result = await response.json();
    return result.ShipmentData?.[0] || null;
  } catch (error) {
    console.error('❌ Delhivery tracking error:', error);
    throw error;
  }
}

/**
 * Check Pincode Serviceability
 */
export async function checkDelhiveryServiceability(pincode: string) {
  try {
    const token = await getDelhiveryToken();
    if (!token) {
      throw new Error('Delhivery API token not configured');
    }

    const response = await fetch(`${DELHIVERY_API_BASE}/c/pin-codes/json/?filter_codes=${pincode}`, {
      headers: {
        'Authorization': `Token ${token}`,
      }
    });

    if (!response.ok) {
      throw new Error('Failed to check serviceability');
    }

    const result = await response.json();
    return result.delivery_codes?.[0] || null;
  } catch (error) {
    console.error('❌ Delhivery serviceability check error:', error);
    throw error;
  }
}

/**
 * Cancel Shipment
 */
export async function cancelDelhiveryShipment(waybill: string) {
  try {
    const token = await getDelhiveryToken();
    if (!token) {
      throw new Error('Delhivery API token not configured');
    }

    const response = await fetch(`${DELHIVERY_API_BASE}/p/edit`, {
      method: 'POST',
      headers: {
        'Authorization': `Token ${token}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        waybill: waybill,
        cancellation: true
      })
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Delhivery cancellation failed: ${JSON.stringify(error)}`);
    }

    const result = await response.json();
    console.log('✅ Delhivery shipment cancelled:', waybill);
    return result;
  } catch (error) {
    console.error('❌ Delhivery cancellation error:', error);
    throw error;
  }
}

/**
 * Create Pickup Request
 */
export async function createDelhiveryPickup(pickupData: any) {
  try {
    const token = await getDelhiveryToken();
    if (!token) {
      throw new Error('Delhivery API token not configured');
    }

    const formData = new URLSearchParams();
    formData.append('pickup_location', JSON.stringify({
      name: pickupData.locationName,
      add: pickupData.address.street,
      city: pickupData.address.city,
      pin_code: pickupData.address.pincode,
      country: 'India',
      phone: pickupData.phone
    }));
    formData.append('pickup_date', pickupData.pickupDate);
    formData.append('pickup_time', pickupData.pickupTime);

    const response = await fetch(`${DELHIVERY_API_BASE}/fm/request/new/`, {
      method: 'POST',
      headers: {
        'Authorization': `Token ${token}`,
        'Content-Type': 'application/x-www-form-urlencoded',
      },
      body: formData.toString()
    });

    if (!response.ok) {
      const error = await response.json();
      throw new Error(`Delhivery pickup creation failed: ${JSON.stringify(error)}`);
    }

    const result = await response.json();
    console.log('✅ Delhivery pickup created');
    return result;
  } catch (error) {
    console.error('❌ Delhivery pickup creation error:', error);
    throw error;
  }
}

/**
 * Get Shipping Label
 */
export async function getDelhiveryLabel(waybill: string) {
  try {
    const token = await getDelhiveryToken();
    if (!token) {
      throw new Error('Delhivery API token not configured');
    }

    const response = await fetch(`${DELHIVERY_API_BASE}/p/packing_slip?wbns=${waybill}`, {
      headers: {
        'Authorization': `Token ${token}`,
      }
    });

    if (!response.ok) {
      throw new Error('Failed to get shipping label');
    }

    return await response.text(); // Returns HTML
  } catch (error) {
    console.error('❌ Delhivery label fetch error:', error);
    throw error;
  }
}

/**
 * Delhivery Endpoints for Hono
 */
export function registerDelhiveryIntegration(app: Hono) {
  
  /**
   * GET /delhivery/config
   * Get Delhivery configuration status
   */
  app.get('/make-server-3dd53475/delhivery/config', async (c) => {
    try {
      const token = await getDelhiveryToken();
      return c.json({
        success: true,
        enabled: !!token
      });
    } catch (error: any) {
      console.error('Error fetching Delhivery config:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  /**
   * POST /delhivery/shipments/create
   * Create Delhivery shipment
   */
  app.post('/make-server-3dd53475/delhivery/shipments/create', async (c) => {
    try {
      const orderData = await c.req.json();
      const result = await createDelhiveryShipment(orderData);
      
      return c.json({
        success: true,
        data: result
      });
    } catch (error: any) {
      console.error('Error creating Delhivery shipment:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  /**
   * GET /delhivery/shipments/track/:waybill
   * Track Delhivery shipment
   */
  app.get('/make-server-3dd53475/delhivery/shipments/track/:waybill', async (c) => {
    try {
      const waybill = c.req.param('waybill');
      const trackingData = await trackDelhiveryShipment(waybill);
      
      return c.json({
        success: true,
        trackingData
      });
    } catch (error: any) {
      console.error('Error tracking Delhivery shipment:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  /**
   * POST /delhivery/pincode/check
   * Check pincode serviceability
   */
  app.post('/make-server-3dd53475/delhivery/pincode/check', async (c) => {
    try {
      const { pincode } = await c.req.json();
      const result = await checkDelhiveryServiceability(pincode);
      
      return c.json({
        success: true,
        serviceable: !!result,
        data: result
      });
    } catch (error: any) {
      console.error('Error checking Delhivery serviceability:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  /**
   * POST /delhivery/shipments/cancel
   * Cancel Delhivery shipment
   */
  app.post('/make-server-3dd53475/delhivery/shipments/cancel', async (c) => {
    try {
      const { waybill } = await c.req.json();
      const result = await cancelDelhiveryShipment(waybill);
      
      return c.json({
        success: true,
        data: result
      });
    } catch (error: any) {
      console.error('Error cancelling Delhivery shipment:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  /**
   * POST /delhivery/pickup/create
   * Create pickup request
   */
  app.post('/make-server-3dd53475/delhivery/pickup/create', async (c) => {
    try {
      const pickupData = await c.req.json();
      const result = await createDelhiveryPickup(pickupData);
      
      return c.json({
        success: true,
        data: result
      });
    } catch (error: any) {
      console.error('Error creating Delhivery pickup:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  /**
   * GET /delhivery/label/:waybill
   * Get shipping label
   */
  app.get('/make-server-3dd53475/delhivery/label/:waybill', async (c) => {
    try {
      const waybill = c.req.param('waybill');
      const labelHtml = await getDelhiveryLabel(waybill);
      
      return c.html(labelHtml);
    } catch (error: any) {
      console.error('Error fetching Delhivery label:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  /**
   * POST /delhivery/webhook
   * Handle Delhivery webhooks
   */
  app.post('/make-server-3dd53475/delhivery/webhook', async (c) => {
    try {
      const body = await c.req.json();
      
      console.log('📦 Delhivery webhook received:', body);
      
      // ✅ SQL: Store webhook event in logistics_webhooks table (if exists) or skip
      const db = getDbClient();
      try {
        await db.from('logistics_webhooks').insert({
          partner_id: 'delhivery',
          webhook_type: body.status || 'unknown',
          webhook_data: body,
          received_at: new Date().toISOString()
        });
      } catch (error) {
        // Table might not exist yet, log webhook data
        console.log('[Delhivery] Webhook received (stored in logs only):', body);
      }
      
      return c.json({ success: true });
    } catch (error: any) {
      console.error('Error handling Delhivery webhook:', error);
      return c.json({ error: error.message }, 500);
    }
  });

  console.log('✅ Delhivery endpoints registered');
}
