/**
 * Predefined dog and cat breed lists for pet profile creation
 */

export const DOG_BREEDS: string[] = [
  'Labrador Retriever',
  'Golden Retriever',
  'German Shepherd',
  'French Bulldog',
  'Bulldog',
  'Poodle',
  'Beagle',
  'Rottweiler',
  'German Shorthaired Pointer',
  'Yorkshire Terrier',
  'Boxer',
  'Dachshund',
  'Siberian Husky',
  'Great Dane',
  'Doberman Pinscher',
  'Australian Shepherd',
  'Miniature Schnauzer',
  'Cavalier King Charles Spaniel',
  'Shih Tzu',
  'Boston Terrier',
  'Pomeranian',
  'Havanese',
  'English Springer Spaniel',
  'Shetland Sheepdog',
  'Brittany',
  'Cocker Spaniel',
  'Border Collie',
  'Maltese',
  'Bernese Mountain Dog',
  'Basset Hound',
  'Weimaraner',
  'Vizsla',
  'Chihuahua',
  'Pug',
  'Mastiff',
  'Belgian Malinois',
  'Collie',
  'Newfoundland',
  'Rhodesian Ridgeback',
  'West Highland White Terrier',
  'Australian Cattle Dog',
  'Shiba Inu',
  'Bichon Frise',
  'English Setter',
  'Bloodhound',
  'Samoyed',
  'Alaskan Malamute',
  'Italian Greyhound',
  'Chinese Crested',
  'Papillon',
  'Irish Setter',
  'Akita',
  'Basenji',
  'Whippet',
  'Scottish Terrier',
  'Airedale Terrier',
  'Staffordshire Bull Terrier',
  'Cane Corso',
  'Bull Terrier',
  'Shar Pei',
  'Soft Coated Wheaten Terrier',
  'Dalmatian',
  'Greyhound',
  'Wirehaired Pointing Griffon',
  'Irish Wolfhound',
  'Afghan Hound',
  'Great Pyrenees',
  'Saint Bernard',
  'Old English Sheepdog',
  'Bullmastiff',
  'Giant Schnauzer',
  'Smooth Fox Terrier',
  'Tibetan Mastiff',
  'Australian Terrier',
  'Standard Schnauzer',
  'Curly-Coated Retriever',
  'Norfolk Terrier',
  'Affenpinscher',
  'Brussels Griffon',
  'Pembroke Welsh Corgi',
  'Cardigan Welsh Corgi',
  'Border Terrier',
  'Norwich Terrier',
  'Silky Terrier',
  'Toy Fox Terrier',
  'Parson Russell Terrier',
  'American Eskimo Dog',
  'Lhasa Apso',
  'Schipperke',
  'Tibetan Terrier',
  'Japanese Chin',
  'Pekingese',
  'Shih Tzu',
  'Tibetan Spaniel',
  'Pug',
  'French Bulldog',
  'Boston Terrier',
  'Bulldog',
  'Boxer',
  'Great Dane',
  'Mastiff',
  'Neapolitan Mastiff',
  'English Mastiff',
  'Bull Terrier',
  'Staffordshire Bull Terrier',
  'American Pit Bull Terrier',
  'American Staffordshire Terrier',
  'Rottweiler',
  'Doberman Pinscher',
  'German Shepherd',
  'Belgian Malinois',
  'Dutch Shepherd',
  'Cane Corso',
  'Dogo Argentino',
  'Fila Brasileiro',
  'Tosa Inu',
  'Akita',
  'Shiba Inu',
  'Chow Chow',
  'Shar Pei',
  'Indian Spitz',
  'Indian Pariah Dog',
  'Rajapalayam',
  'Mudhol Hound',
  'Kanni',
  'Chippiparai',
  'Combai',
  'Rampur Greyhound',
  'Pandikona',
  'Jonangi',
  'Other',
];

export const CAT_BREEDS: string[] = [
  'Persian',
  'Maine Coon',
  'British Shorthair',
  'Ragdoll',
  'Bengal',
  'Abyssinian',
  'Siamese',
  'American Shorthair',
  'Scottish Fold',
  'Sphynx',
  'Russian Blue',
  'Norwegian Forest Cat',
  'Devon Rex',
  'Exotic Shorthair',
  'Oriental Shorthair',
  'Turkish Angora',
  'Birman',
  'Himalayan',
  'American Curl',
  'Cornish Rex',
  'Chartreux',
  'Tonkinese',
  'Burmese',
  'Manx',
  'Somali',
  'Balinese',
  'Egyptian Mau',
  'Japanese Bobtail',
  'Selkirk Rex',
  'LaPerm',
  'Munchkin',
  'Savannah',
  'Ocicat',
  'Singapura',
  'Peterbald',
  'Toyger',
  'Bombay',
  'Colorpoint Shorthair',
  'Havana Brown',
  'Korat',
  'Lykoi',
  'Pixie-bob',
  'Ragamuffin',
  'Siberian',
  'Turkish Van',
  'American Bobtail',
  'Cymric',
  'Highlander',
  'Khao Manee',
  'Nebelung',
  'Serengeti',
  'Snowshoe',
  'Thai',
  'Ukrainian Levkoy',
  'Indian Domestic Shorthair',
  'Indian Domestic Longhair',
  'Other',
];
